languageCode: "en-us"
title: "Diary of Service Deployment"
theme: "PaperMod" # Change based on your theme
pluralizelisttitles: false

modules:
  hugoVersion: "0.124.1"

minify:
  disableXML: true
  minifyOutput: true

pagination:
  pagerSize: 20

markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    style: syntax-highlight
    tabWidth: 4
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false


params:
  showPostNavLinks: true
  showCodeCopyButtons: true
  homeInfoParams:
    Title: "Welcome to My Diary of Service Deployment"
    Content: 
      "This is my diary of service deployment. Such collection of notes and posts were created with the goal of making it somewhat easier to get tips and tricks while sharing experince and guidence with others. My hope that this on one day helps some to not explode in anger or deepdive into depression on the possible failures of deploying services. \n\n\n The services here are most of the time will be contanerized, thus a simlpe user, or a kubernetes cluster user could deploy them. Docker is loveable.\n\n\nHave a great time exploring!\n- Adam"
  mainSections:
    - "Home"

  UseHugoToc: true
  showtoc: true
  tocopen: false

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Services"
      url: "/services/"
      weight: 2

taxonomies:
  tag: "tags"
  category: "categories"

outputs:
  home: ["HTML", "RSS", "JSON"]
  page: ["HTML"]
  section: ["HTML", "RSS"]
  taxonomy: ["HTML", "RSS"]
  term: ["HTML", "RSS"]