services:
  hugo:
    build: 
      context: ..
      dockerfile: docker/Dockerfile  # Use the correct Dockerfile location
    container_name: mynotes_hugo
    working_dir: /app  # Set the working directory
    ports:
      - "1313:1313"
    volumes:
      - ../site:/app  # Mount the 'site' folder properly
    env_file:
      - ../.env
    restart: unless-stopped
